parameters:
#    js_power_admin_web.example.class: jsPowerAdmin\WebBundle\Example
    js_power_admin_web.ui:
        # NOTE: Do not change! Used by UI drop downs.
        record_types:
                - type: A
                  id: 1
                - type: AAAA
                  id: 2
                - type: CNAME
                  id: 3
                - type: HINFO
                  id: 4
                - type: MX
                  id: 5
                - type: NAPTR
                  id: 6
                - type: NS
                  id: 7
                - type: PTR
                  id: 8
                - type: SOA
                  id: 9
                - type: SPF
                  id: 10
                - type: SRV
                  id: 11
                - type: SSHFP
                  id: 12
                - type: TXT
                  id: 13
                - type: RP
                  id: 14
        # NOTE: Do not change! Used by UI drop downs.
        master_zone_types:
                - type: master
                  id: 1
                - type: native
                  id: 2
        # NOTE: Do not change! YUsed by UI fields.
        record_defaults:
                prio: 1
                ttl: 86400
        # NOTE: The "production" user interface version is loading Ext JS from a CDN. Configurable here, to allow for easy version updates.
        extjs_cdn_url: http://cdn.sencha.io/ext-4.2.0-gpl/ext-all.js
        # Date format, used by the UI.
        date_format: 'd/M/y H:i:s'
services:
#    js_power_admin_web.example:
#        class: %js_power_admin_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]