parameters:
#    js_power_admin_web.example.class: jsPowerAdmin\WebBundle\Example

services:
#    js_power_admin_web.example:
#        class: %js_power_admin_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
