jsPowerAdmin\WebBundle\Entity\Domains:
    type: entity
    table: domains
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        master:
            type: string
            nullable: true
            length: 128
            fixed: false
            comment: ''
        lastCheck:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: last_check
        type:
            type: string
            nullable: false
            length: 6
            fixed: false
            comment: ''
        notifiedSerial:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: notified_serial
        account:
            type: string
            nullable: true
            length: 40
            fixed: false
            comment: ''
    oneToMany:
        records:
            targetEntity: Records
            mappedBy: domain
#                 cascade: ["persist", "merge"]
    lifecycleCallbacks: {  }
